/*
 * CloseOutPosition.java
 *
 * Created on June 3, 2014, 11:55 PM
 */
package share_trading_journal.resources;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author  Ravi Patel
 */
public class CloseOutPosition extends javax.swing.JFrame {
    
    /** Creates new form CloseOutPosition */
    String sc="",ssc="";
    double strike1=0.0,strike2=0.0;
    double breakeven = 0.0;
    public CloseOutPosition(String sc,String ssc) {

        initComponents();
        this.sc=sc;
        this.ssc = ssc;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby:database/share_trading");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Break_Even,Expire_Month_CO,Strike_Price_CO,Expire_Month_PO,Strike_Price_PO from new_trade where Stock_Code='"+ssc+"' and cnt="+Utility.cnt);

            while(rs.next())
            {
                 breakeven = rs.getDouble("Break_Even");
                 lblmonth1.setText(rs.getString("Expire_Month_CO"));
                 strike1=rs.getDouble("Strike_Price_CO");
                 lblstrike1.setText("$"+String.format("%,.2f",strike1));

                 lblmonth2.setText(rs.getString("Expire_Month_PO"));
                 strike2=rs.getDouble("Strike_Price_PO");
                 lblstrike2.setText("$"+String.format("%,.2f",strike2));
            }

            st.close();
            con.close();
        }
        catch(Exception e)
        {
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtbrokerage = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtstockprice = new javax.swing.JTextField();
        btnclose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtpremium1 = new javax.swing.JTextField();
        txtpremium2 = new javax.swing.JTextField();
        lblstrike1 = new javax.swing.JLabel();
        lblmonth1 = new javax.swing.JLabel();
        lblmonth2 = new javax.swing.JLabel();
        lblstrike2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Close Out Position");
        setIconImage(new ImageIcon("images/Sharelord_logo.png").getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("Close Out Position");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel14.setText("Brokerage");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel15.setText("Stock Price");

        btnclose.setFont(new java.awt.Font("Arial", 0, 18));
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        btnclose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncloseKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel8.setText("Type");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel9.setText("Month");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel12.setText("Strike");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel13.setText("Premium");

        lblstrike1.setFont(new java.awt.Font("Arial", 0, 14));

        lblmonth1.setFont(new java.awt.Font("Arial", 0, 14));

        lblmonth2.setFont(new java.awt.Font("Arial", 0, 14));

        lblstrike2.setFont(new java.awt.Font("Arial", 0, 14));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel16.setText("Close Call Option");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel17.setText("Close Put Option");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblmonth1)
                    .addComponent(lblmonth2))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lblstrike1)
                    .addComponent(lblstrike2))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtpremium2)
                    .addComponent(txtpremium1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmonth1)
                    .addComponent(lblstrike1)
                    .addComponent(jLabel16)
                    .addComponent(txtpremium1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmonth2)
                    .addComponent(lblstrike2)
                    .addComponent(txtpremium2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btncancel.setFont(new java.awt.Font("Arial", 0, 18));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        btncancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncancelKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnclose)
                                    .addGap(18, 18, 18)
                                    .addComponent(btncancel))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbrokerage)
                            .addComponent(txtstockprice, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtstockprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtbrokerage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnclose))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btncloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncloseKeyPressed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btncloseKeyPressed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btncancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncancelKeyPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelKeyPressed
    public void close()
    {
        try
        {
            String copremium=txtpremium1.getText();
            String popremium=txtpremium2.getText();

            SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
            String date = sd.format(new Date());

            Connection con = DriverManager.getConnection("jdbc:derby:database/share_trading");
            PreparedStatement pst = con.prepareStatement("insert into intervention values(?,?,?,?,?,?,?,?,?,?,?)");

            double coPremium = 0.0;
            double poPremium = 0.0;
            
            if(!(copremium.equals("") || txtstockprice.getText().equals("") || txtbrokerage.getText().equals("")))
            {
                pst.setString(1,date);
                pst.setString(2,"Close Out Position");
                pst.setString(3,"Call");
                pst.setString(4,lblmonth1.getText());
                pst.setDouble(5,strike1);
                coPremium =Double.parseDouble(copremium);
                pst.setDouble(6,coPremium);
                pst.setString(7,"");
                pst.setDouble(8,0.0);
                pst.setDouble(9,0.0);
                pst.setDouble(10,Double.parseDouble(txtbrokerage.getText()));
                pst.setString(11,sc);

                pst.executeUpdate();

                if(!popremium.equals(""))
                {
                    pst.setString(3,"Put");
                    pst.setString(4,lblmonth2.getText());
                    pst.setDouble(5,strike2);
                    poPremium = Double.parseDouble(popremium);
                    pst.setDouble(6,poPremium);

                    pst.executeUpdate();
                }

                Utility.updateStockSoldPrice(Double.parseDouble(txtstockprice.getText()),ssc);
                Utility.updateBreakEven(breakeven+coPremium-poPremium, ssc);
                Utility.updateOutcome("Close Out Position", "Close",ssc);
                JOptionPane.showMessageDialog(this,"Close Out Position Successfully...Trade is Closed.");
                 this.dispose();
            }
            else
            {
                    String msg = "";
                    if(copremium.equals(""))
                        msg+="\n->Close Call Option Premium";
                    if(txtstockprice.getText().equals(""))
                        msg+="\n->Stock Price";
                    if(txtbrokerage.getText().equals(""))
                        msg+="\n->Brokerage";

                    JOptionPane.showMessageDialog(this,"Following Fields are empty:"+msg);
            }

            pst.close();
            con.close();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, e+"Pease Enter Numeric value...");
        }
        catch(Exception e)
        {
                JOptionPane.showMessageDialog(this, e);
        }
       
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblmonth1;
    private javax.swing.JLabel lblmonth2;
    private javax.swing.JLabel lblstrike1;
    private javax.swing.JLabel lblstrike2;
    private javax.swing.JTextField txtbrokerage;
    private javax.swing.JTextField txtpremium1;
    private javax.swing.JTextField txtpremium2;
    private javax.swing.JTextField txtstockprice;
    // End of variables declaration//GEN-END:variables
    
}
