/*
 * InsureButPutOption.java
 *
 * Created on June 4, 2014, 10:07 AM
 */

package share_trading_journal.resources;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author  Ravi Patel
 */
public class InsureBuyPutOption extends javax.swing.JFrame {
    
    /** Creates new form InsureButPutOption */
    double curr_break_even=0.0;
    String sc="",ssc="";
    public InsureBuyPutOption(String sc,String ssc) {
        initComponents();
        this.sc=sc;
        this.ssc = ssc;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        dppomonth.setFormats("MMM dd ''yy");
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby:database/share_trading");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select Break_Even from new_trade where Stock_Code='"+ssc+"' and cnt="+Utility.cnt);

            while(rs.next())
            {
                 curr_break_even = rs.getDouble("Break_Even");
            }

            st.close();
            con.close();
        }
        catch(Exception e)
        {
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtbrokerage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstrike = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpremium = new javax.swing.JTextField();
        btninsure = new javax.swing.JButton();
        dppomonth = new org.jdesktop.swingx.JXDatePicker();
        btncancel3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insure-Buy Put Option");
        setIconImage(new ImageIcon("images/Sharelord_logo.png").getImage());
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("Insure - Buy Put Option");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel15.setText("Buy Put Option");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel14.setText("Brokerage");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel4.setText("Month");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel5.setText("Strike");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel6.setText("Premium");

        btninsure.setFont(new java.awt.Font("Arial", 0, 18));
        btninsure.setText("Insure");
        btninsure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsureActionPerformed(evt);
            }
        });
        btninsure.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btninsureKeyPressed(evt);
            }
        });

        dppomonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dppomonthActionPerformed(evt);
            }
        });

        btncancel3.setFont(new java.awt.Font("Arial", 0, 18));
        btncancel3.setText("Cancel");
        btncancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel3ActionPerformed(evt);
            }
        });
        btncancel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btncancel3KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(71, 71, 71))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dppomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtstrike, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpremium, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(txtbrokerage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(btninsure, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncancel3)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstrike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dppomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbrokerage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel3)
                    .addComponent(btninsure))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsureActionPerformed
        // TODO add your handling code here:
        insure();
        
    }//GEN-LAST:event_btninsureActionPerformed

    private void dppomonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dppomonthActionPerformed
        // TODO add your handling code here:
        if(!dppomonth.getDate().toString().contains("Fri")) {
            JOptionPane.showMessageDialog(this,"Please Select Friday Only...");
            dppomonth.setDate(null);
        }
    }//GEN-LAST:event_dppomonthActionPerformed

    private void btninsureKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btninsureKeyPressed
        // TODO add your handling code here:
        insure();
    }//GEN-LAST:event_btninsureKeyPressed

    private void btncancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btncancel3ActionPerformed

    private void btncancel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncancel3KeyPressed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_btncancel3KeyPressed
    public void insure()
    {
        /*Validator v=new Validator();
        v.add(txtpremium);
        v.add(txtstrike);
        v.add(txtbrokerage);

        if(v.isValidate() && dppomonth.getDate()!=null)
        {*/
            try
            {
                String popremium1=txtpremium.getText();

                Date pomonth=dppomonth.getDate();
                String postrike=txtstrike.getText();

                SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
                String date = sd.format(new Date());

                Connection con = DriverManager.getConnection("jdbc:derby:database/share_trading");
                PreparedStatement pst = con.prepareStatement("insert into intervention values(?,?,?,?,?,?,?,?,?,?,?)");

                if(!(popremium1.equals("") || postrike.equals("") || pomonth==null || txtbrokerage.getText().equals("")))
                {
                    pst.setString(1,date);
                    pst.setString(2,"New Position");
                    pst.setString(3,"Put");
                    pst.setString(4,"");
                    pst.setDouble(5,0.0);
                    pst.setDouble(6,0.0);
                    sd = new SimpleDateFormat("MMM dd ''yy");
                    pst.setString(7,sd.format(pomonth));
                    pst.setDouble(8,Double.parseDouble(postrike));
                    pst.setDouble(9,Double.parseDouble(popremium1));
                    pst.setDouble(10,Double.parseDouble(txtbrokerage.getText()));
                    pst.setString(11,sc);

                    curr_break_even+=Double.parseDouble(popremium1);
                    Utility.updateBreakEven(curr_break_even,ssc);
                    Utility.updatePut(sd.format(pomonth), Double.parseDouble(postrike), Double.parseDouble(popremium1),ssc);

                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Insure - Buy Put Option Successfully...");
                    this.dispose();
                }
                else
                {
                         String msg = "";
                     if(pomonth==null)
                        msg+="\n->Sell Call Option Month";
                    if(postrike.equals(""))
                        msg+="\n->Sell Call Option Strike";
                    if(popremium1.equals(""))
                        msg+="\n->Sell Call Option Premium";
                    if(txtbrokerage.getText().equals(""))
                        msg+="\n->Brokerage";

                    JOptionPane.showMessageDialog(this,"Following Put Option Fields are empty:"+msg);
                }

                pst.close();
                con.close();
                
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(this, e+"\nEnter Only numeric value...");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
        /*}
        else
        {
            JOptionPane.showMessageDialog(this, "All fields are Compulsory!");
        }*/
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel3;
    private javax.swing.JButton btninsure;
    private org.jdesktop.swingx.JXDatePicker dppomonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtbrokerage;
    private javax.swing.JTextField txtpremium;
    private javax.swing.JTextField txtstrike;
    // End of variables declaration//GEN-END:variables
    
}
